name: Notificações Loterias

on:
  schedule:
    # Executa o script todos os dias às 8h
    - cron: '0 8 * * 1-6'
    # Executa o script todos os dias às 15h
    - cron: '0 15 * * 1-6'
    # Executa o script todos os dias às 18h45
    - cron: '45 18 * * 1-6'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Executar script
        run: |
          python ./Loteria.py  # Caminho correto para a raiz do repositório
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
